VIA_ENABLE = yes
LTO_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
BACKLIGHT_ENABLE = no
ENCODER_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
DYNAMIC_MACRO_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
RGB_MATRIX_CUSTOM_USER = yes
